name: showcaseview
description: A Flutter package to Showcase/Highlight widgets step by step.
version: 1.1.3
homepage: https://github.com/simformsolutions/flutter_showcaseview
issue_tracker: https://github.com/simformsolutions/flutter_showcaseview/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.2

flutter:
