name: showcaseview
description: A Flutter package to Showcase/Highlight widgets step by step.
version: 4.0.2
issue_tracker: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview/issues
repository: https://github.com/simformsolutions/flutter_showcaseview

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

flutter:
